### ISSUE TITLE
波浪线排版问题

### ISSUE THREAD

**Issue by Forcliisay** [JackyZhang00/Computational-Materials-Tutorial#3]
## 波浪线排版问题
表示home的波浪线在文件中以缩小的形式出现。
![image](https://github.com/user-attachments/assets/79011d48-f934-4253-80ba-249ffde68dd6)

**Comment by JackyZhang00** [comment]
已修复。

修复内容：

- 在正文中使用`\texttilde`或`\ttilde`表示波浪线，不再使用`\~`表示；
- 更改`temp.tex`文件内容，增加关于这一命令的说明。

![image](https://github.com/user-attachments/assets/6baea7b7-d6b3-4b48-b934-973201e01bfc)
