### ISSUE TITLE
问题索引

### ISSUE THREAD

**Issue by Forcliisay** [JackyZhang00/Computational-Materials-Tutorial#4]
## 计算中遇到的问题-索引
是否可以考虑在文末建立一个问题索引，方便后续其他团队成员在计算过程中对自己遇到的问题及解决方案进行补充，且方便部分读者根据遇到的计算问题使用该书？
可以的话再加个链接就更好了☝️😎

**Comment by JackyZhang00** [comment]
文末是整本书的最后？还是每一章或每一节的最后？

**Comment by JackyZhang00** [comment]
@Forcliisay 所指**文末**，指的是整本书的最后？还是某一章或某一节的后面？
